name: Robot Pengecek Kode Python

on: [push]

jobs:
  cek-error:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari repository
        uses: actions/checkout@v4

      - name: Siapkan Python dengan Cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # ⬅️ Ini fitur rahasianya

      - name: Install dependencies
        run: pip install -r requirements.txt # ⬅️ Membaca dari file

      - name: Jalankan Tes
        run: pytest test_app.py
